name: App-down

on:
    push:
        branches: [ "main" ]

    workflow_dispatch:

    permissions:
        packages: write
        contents: read

jobs:
    Build-all-images:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
            name: Checkout repository

          - name: "GHCR Push: Build and push Docker image"
            uses: Its4Nik/NGX-action@3.1
            with:
            github-push-secret: ${{secrets.GITHUB_TOKEN}}
            build-only: false